openapi: 3.2.0
info:
  title: Plerion API Documentation AWS integration API
  version: v1
  termsOfService: https://www.plerion.com/terms-and-conditions
  contact:
    name: Plerion Pty Ltd
    url: https://www.plerion.com/contact-us
    email: support@plerion.com
  license:
    name: Plerion Use License
    url: https://www.plerion.com/terms-and-conditions
  description: 'The Plerion API allows you to programmatically interact with Plerion.


    Base URL: https://{region}.api.plerion.com'
servers:
- url: https://{region}.api.plerion.com
  description: Production API server - Select your preferred region
  variables:
    region:
      default: au
      enum:
      - au
      - sg1
      - in1
      - us1
tags:
- name: AWS integration
  x-displayName: AWS Integration
  description: 'In order to connect your AWS account to Plerion or update existing account, you will need,


    CloudFormation Template URL.'
paths:
  /v1/tenant/external-id:
    get:
      tags:
      - AWS integration
      operationId: getExternalId
      summary: Get external id
      x-mint:
        metadata:
          title: Get the external ID of the tenant
      description: 'Use the API to get the external ID of the tenant. The external ID is fixed for a tenant and used for cross-account access to AWS role. Read more about External Id purpose.

        ```bash

        curl "https://au.api.plerion.com/v1/tenant/external-id" -H "Authorization: Bearer $PLERION_API_KEY"

        ```'
      security:
      - APIKey: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/ExternalId'
        '403':
          $ref: '#/components/responses/403'
  /v1/tenant/integrations/token:
    post:
      tags:
      - AWS integration
      operationId: createTemporaryToken
      summary: Generate temporary token
      x-mint:
        metadata:
          title: Generate temporary token for creating AWS integration
      description: 'Use the API to generate a temporary token required for creating AWS integration using CloudFormation template provided by Plerion.

        ```bash

        curl -X POST https://au.api.plerion.com/v1/tenant/integrations/token -H "Authorization: Bearer $PLERION_API_KEY"

        ```'
      security:
      - APIKey: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TemporaryAuthToken'
        '403':
          $ref: '#/components/responses/403'
  /v1/tenant/cloudformation-templates:
    get:
      operationId: getCloudformationTemplate
      tags:
      - AWS integration
      summary: Get CloudFormation template
      description: 'Use the API to get the CloudFormation template required for creating / updating AWS integrations in Plerion.

        ```bash

        curl https://au.api.plerion.com/v1/tenant/cloudformation-templates?type=AWSAccount -H "Authorization: Bearer $PLERION_API_KEY"

        ```'
      security:
      - APIKey: []
      parameters:
      - $ref: '#/components/parameters/paramAuthHeader'
      - in: query
        name: type
        description: The type of integration for which the CloudFormation template is required
        schema:
          type: string
          enum:
          - AWSAccount
          example: AWSAccount
      responses:
        '200':
          description: CloudFormation Template
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      templateURL:
                        type: string
                        example: https://pl-ap-southeast-2-prod-static-policy-bucket.s3.ap-southeast-2.amazonaws.com/templates/aws-account-automated/v12/cloudformation.yaml
                      templateVersion:
                        type: string
                        example: v12
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    TemporaryAuthToken:
      type: object
      properties:
        token:
          type: string
    ExternalId:
      type: object
      properties:
        externalId:
          type: string
    InternalServerErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Internal server error
  parameters:
    paramAuthHeader:
      name: Authorization
      in: header
      description: Bearer API Key. For example, "Bearer {Tenant API Key}"
      required: true
      schema:
        type: string
  responses:
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerErrorResponse'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Forbidden
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                    code:
                      type: string
                    message:
                      type: string
  securitySchemes:
    APIKey:
      type: http
      scheme: bearer
      bearerFormat: apiKey
      description: Bearer API Key. For example, "Bearer {Tenant API Key}"
